--Database schema script.

CREATE DATABASE hrtool_database;


--Creating tables for the database with NOT NULL and UNIQUE conditions on specified columns.

CREATE TABLE TASKS
(
	ID number NOT NULL UNIQUE,
	TITLE varchar(255) NOT NULL,
	DESCRIPTION varchar(2500),
	NOTES varchar(2500),
	COMPLETED boolean NOT NULL,
	DATE_FROM date,
	DATE_TO date,
	USER_ID number,
	BUDDY_ID number
);

CREATE TABLE DEFAULT_TASKS
(
	ID number NOT NULL UNIQUE,
	TITLE varchar(255) NOT NULL,
	DESCRIPTION varchar(2500),
	TEAM_ID number,
	DEPARTMENT_ID number
);

CREATE TABLE USERS
(
	ID number NOT NULL UNIQUE,
	FISRT_NAME varchar(255) NOT NULL,
	LAST_NAME varchar(255) NOT NULL,
	EMAIL varchar(255) NOT NULL UNIQUE,
	ROLE_ID number,
	BUDDY_ID number
);

CREATE TABLE ROLES
(
	ID number NOT NULL UNIQUE,
	TITLE varchar(255) NOT NULL
);

CREATE TABLE USERS_IN_TEAMS
(
	ID number NOT NULL UNIQUE,
	USER_ID number NOT NULL,
	TEAM_ID number NOT NULL
);

CREATE TABLE TEAMS
(
	ID number NOT NULL UNIQUE,
	TITLE varchar(255) NOT NULL,
	DEPARTMENT_ID number
);

CREATE TABLE DEPARTMENTS
(
	ID number NOT NULL UNIQUE,
	TITLE varchar(255) NOT NULL
);

-- Creating primary key constraints on all tables, always set to ID of the particular table.

ALTER TABLE TASKS
ADD CONSTRAINT pk_ID_TASKS PRIMARY KEY (ID);

ALTER TABLE DEFAULT_TASKS
ADD CONSTRAINT pk_ID_DEFAULT_TASKS PRIMARY KEY (ID);

ALTER TABLE USERS
ADD CONSTRAINT pk_ID_USERS PRIMARY KEY (ID);

ALTER TABLE ROLES
ADD CONSTRAINT pk_ID_ROLES PRIMARY KEY (ID);

ALTER TABLE USERS_IN_TEAMS
ADD CONSTRAINT pk_ID_USERS_IN_TEAMS PRIMARY KEY (ID);

ALTER TABLE TEAMS
ADD CONSTRAINT pk_ID_TEAMS PRIMARY KEY (ID);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT pk_ID_DEPARTMENTS PRIMARY KEY (ID);

-- Creating foreign key constraints on all tables.

-- Foreign key from USER_ID column of TASKS table to ID column from USERS table.
ALTER TABLE TASKS
ADD CONSTRAINT fk_TASKS_USER_ID
FOREIGN KEY (USER_ID)
REFERENCES USERS(ID);

-- Foreign key from BUDDY_ID column of TASKS table to ID column from USERS table.
ALTER TABLE TASKS
ADD CONSTRAINT fk_TASKS_BUDDY_ID
FOREIGN KEY (BUDDY_ID)
REFERENCES USERS(ID);

-- Foreign key from TEAM_ID column of DEFAULT_TASKS table to ID column from TEAMS table.
ALTER TABLE DEFAULT_TASKS
ADD CONSTRAINT fk_DEFAULT_TASKS_TEAM_ID
FOREIGN KEY (TEAM_ID)
REFERENCES TEAMS(ID);

-- Foreign key from DEPARTMENT_ID column of DEFAULT_TASKS table to ID column from DEPARTMENTS table.
ALTER TABLE DEFAULT_TASKS
ADD CONSTRAINT fk_DEFAULT_TASKS_DEPARTMENT_ID
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(ID);

-- Foreign key from ROLE_ID column of USERS table to ID column from ROLES table.
ALTER TABLE USERS
ADD CONSTRAINT fk_USERS_ROLE_ID
FOREIGN KEY (ROLE_ID)
REFERENCES ROLES(ID);

-- Foreign key from BUDDY_ID column of USERS table to ID column from USERS table.
ALTER TABLE USERS
ADD CONSTRAINT fk_USERS_BUDDY_ID
FOREIGN KEY (BUDDY_ID)
REFERENCES USERS(ID);

-- Foreign key from USER_ID column of USERS_IN_TEAMS table to ID column from USERS table.
ALTER TABLE USERS_IN_TEAMS
ADD CONSTRAINT fk_USERS_IN_TEAMS_USER_ID
FOREIGN KEY (USER_ID)
REFERENCES USERS(ID);

-- Foreign key from TEAM_ID column of USERS_IN_TEAMS table to ID column from TEAMS table.
ALTER TABLE USERS_IN_TEAMS
ADD CONSTRAINT fk_USERS_IN_TEAMS_TEAM_ID
FOREIGN KEY (TEAM_ID)
REFERENCES TEAMS(ID);

-- Foreign key from DEPARTMENT_ID column of TEAMS table to ID column from DEPARTMENTS table.
ALTER TABLE TEAMS
ADD CONSTRAINT fk_TEAMS_DEPARTMENT_ID
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(ID)